name: Actaeon Art
favicon: null
layout_spectrum: 0.27131
typography_spectrum: 0.61787
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#004459'
    - '#eeeecc'
    - '#ec4556'
    - '#eb8c7a'
    - '#008a96'
  brandStrength: 0.1875
  lightness: 0.125
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
